version : "3"

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/etc/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web_front
  rest_api:
    container_name: rest_api
    build:
      context: ./python
    env_file:
      - .env
    volumes:
      - ./code/rest_api:/code/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code/ink_compile:/share/
    tty: true
    ports: 
      - 8000:8000
  web_front:
    container_name: web_front
    build:
      context: ./node
    env_file:
      - .env
    volumes:
      - ./code/web_front:/code
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - rest_api

volumes:
  django_data_volume:
