# Generated by Django 2.2.5 on 2019-10-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
